# Build and deploy DocC to GitHub pages. Based off of @karwa's work here:
# https://github.com/karwa/swift-url/blob/main/.github/workflows/docs.yml
# and PointFree's work here:
# https://github.com/pointfreeco/swift-composable-architecture/blob/main/.github/workflows/documentation.yml  
name: Docs

on:
  release:
    types:
      - published
  push:
    paths:
      - '.github/workflows/docs.yml'    
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/docs.yml'        
  workflow_dispatch:

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Select Xcode 15.2
        run: sudo xcode-select -s /Applications/Xcode_15.2.app
  
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout docs branch
        uses: actions/checkout@v4
        with:
          ref: docs
          path: docs-out

      - name: Build documentation
        run: >
          rm -rf docs-out/.git;        
          rm -rf docs-out/main;
          git tag -l --sort=-v:refname | grep -e "\d\+\.\d\+.0" | tail -n +6 | xargs -I {} rm -rf {};
  
          for tag in $(echo "main"; git tag -l --sort=-v:refname | grep -e "\d\+\.\d\+.0" | head -6);
          do
            if [ -d "docs-out/$tag/data/documentation/networking" ] 
            then 
              echo "✅ Documentation for $tag already exists.";
            else 
              echo "⏳ Generating documentation for Networking @ $tag release.";
              rm -rf "docs-out/$tag";

              git checkout .;
              git checkout "$tag";
  
              swift package \
                --allow-writing-to-directory docs-out/"$tag" \
                generate-documentation \
                --target Networking \
                --output-path docs-out/"$tag" \
                --transform-for-static-hosting \
                --hosting-base-path /swift-networking/"$tag" \
                && echo "✅ Documentation generated for Networking @ $tag release." \
                || echo "⚠️ Documentation skipped for Networking @ $tag.";
            fi;
          done
  
      - name: Configure Pages
        id: pages
        uses: actions/configure-pages@v5
        
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs-out
  
  deploy:
    runs-on: ubuntu-latest    
    needs: build    
    permissions:
      pages: write
      id-token: write        
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
